# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import collections.abc
import typing
__all__ = [
    "Context",
    "Operation",
]

@typing.final
class Context:
    r"""
    io_uring AIO context.
    
    `engine`/`registry` are `Mutex`-wrapped, and every method below takes
    `&self` (never `&mut self`), even though nothing here is actually
    touched from more than one OS thread: a callback invoked from
    `deliver()` can reentrantly call back into `submit()`/`flush()`/
    `process_events()` on this same Context (nothing stops user code from
    doing that), and PyO3 enforces Rust's exclusive-borrow rule on
    `&mut self` pyclass methods at runtime - a reentrant call while an
    outer `&mut self` call was still "on the stack" would hit a spurious
    "already borrowed" error. Locking a plain `Mutex` internally (and
    releasing it *before* invoking any callback - see `deliver`'s own doc
    comment) sidesteps that entirely, matching `thread_aio`/`linux_aio`'s
    own bridges.
    """
    @property
    def max_requests(self) -> builtins.int: ...
    @property
    def fileno(self) -> builtins.int: ...
    def __new__(cls, max_requests: builtins.int = 0, sqpoll: builtins.bool = False) -> Context: ...
    def __repr__(self) -> builtins.str: ...
    def submit(self, *ops: Operation) -> builtins.int: ...
    def flush(self) -> builtins.int:
        r"""
        Submits all pending SQEs to the kernel in one `io_uring_enter` call
        (or wakes the SQPOLL thread), then drains whatever completed inline.
        """
    def cancel(self, operation: Operation) -> builtins.int: ...
    def process_events(self, max_requests: builtins.int = 0, min_requests: builtins.int = 0, timeout: builtins.int = 0) -> builtins.int: ...
    def poll(self) -> builtins.int: ...

@typing.final
class Operation:
    r"""
    io_uring operation representation.
    
    One-shot (design doc decision #4), same as `thread_aio`/`linux_aio`'s
    `AIOOperation` - resubmitting the same completed object is no longer
    possible (the pre-`caio-core` implementation *did* allow this, unlike
    `thread_aio`; that's the one intentional behavioral change this move
    makes here). The buffer no longer needs to be a replaceable slot
    re-installed on every submission either, since there is no "every"
    anymore - it's allocated once, in `prepare()` at actual submission
    time, and lives and dies with this one `Operation` (see the design
    doc's "Buffer policy" section: a Rust-owned `Box<[u8]>` now, not the
    old raw-CPython-API zero-copy `bytes` object).
    """
    @property
    def fileno(self) -> builtins.int: ...
    @property
    def offset(self) -> builtins.int: ...
    @property
    def nbytes(self) -> builtins.int: ...
    @property
    def result(self) -> builtins.int: ...
    @property
    def error(self) -> builtins.int: ...
    @property
    def payload(self) -> bytes | None: ...
    @staticmethod
    def read(nbytes: builtins.int, fd: builtins.int, offset: builtins.int, priority: builtins.int = 0) -> Operation: ...
    @staticmethod
    def write(payload_bytes: bytes, fd: builtins.int, offset: builtins.int, priority: builtins.int = 0) -> Operation: ...
    @staticmethod
    def fsync(fd: builtins.int, priority: builtins.int = 0) -> Operation: ...
    @staticmethod
    def fdsync(fd: builtins.int, priority: builtins.int = 0) -> Operation: ...
    def get_value(self) -> bytes | int: ...
    def set_callback(self, callback: collections.abc.Callable[[int], typing.Any]) -> bool: ...
    def __repr__(self) -> builtins.str: ...

