# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import collections.abc
import typing
__all__ = [
    "Context",
    "Operation",
]

@typing.final
class Context:
    r"""
    thread aio context
    """
    @property
    def max_requests(self) -> builtins.int: ...
    @property
    def pool_size(self) -> builtins.int: ...
    def __new__(cls, max_requests: builtins.int = 0, pool_size: builtins.int = 0) -> Context: ...
    def __repr__(self) -> builtins.str: ...
    def submit(self, *ops: Operation) -> builtins.int: ...
    def cancel(self, *ops: Operation) -> builtins.int:
        r"""
        Always ends up reporting 0 cancelled, same as this backend's
        existing behavior - but now because `ThreadDriver` genuinely can't
        interrupt a dispatched request (`supports_inflight_cancel()` is
        `false`, so `Engine::cancel()` always answers `Unsupported`), not
        because this method skips actually trying.
        """

@typing.final
class Operation:
    r"""
    thread aio operation representation.
    
    One-shot (design doc decision #4): `request_id` starts `None` and is
    set exactly once, the moment `Context::submit()` gets this operation
    accepted by the engine. `submit()` checks this *before* even building a
    `RequestSpec` and rejects (silently skips, matching this backend's
    existing behavior) anything that already has one - there is no
    separate "already used" flag because `request_id.is_some()` already is
    that flag. An operation that was *attempted* but *rejected* (e.g. the
    pool's queue was full) never gets a `request_id` at all, so it stays
    fully retryable - only an actually-accepted submission consumes it.
    """
    @property
    def fileno(self) -> builtins.int: ...
    @property
    def offset(self) -> builtins.int: ...
    @property
    def nbytes(self) -> builtins.int: ...
    @property
    def result(self) -> builtins.int: ...
    @property
    def error(self) -> builtins.int: ...
    @property
    def payload(self) -> bytes | memoryview | None: ...
    @staticmethod
    def read(nbytes: builtins.int, fd: builtins.int, offset: builtins.int, priority: builtins.int = 0) -> Operation: ...
    @staticmethod
    def write(payload_bytes: bytes, fd: builtins.int, offset: builtins.int, priority: builtins.int = 0) -> Operation: ...
    @staticmethod
    def fsync(fd: builtins.int, priority: builtins.int = 0) -> Operation: ...
    @staticmethod
    def fdsync(fd: builtins.int, priority: builtins.int = 0) -> Operation: ...
    def get_value(self) -> bytes | int: ...
    def set_callback(self, callback: collections.abc.Callable[[int], typing.Any]) -> bool: ...
    def __repr__(self) -> builtins.str: ...

